import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "mock_snowflake.db")

def create_db():
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Enable foreign keys
    cursor.execute("PRAGMA foreign_keys = ON;")

    print("Creating tables...")

    # DIM_SOURCE_PRODUCT
    cursor.execute("""
    CREATE TABLE DIM_SOURCE_PRODUCT (
        SOURCE_PRODUCT_ID TEXT PRIMARY KEY,
        EOG_COMBI TEXT,
        NFC_HASH_ID TEXT,
        FCC_CD TEXT,
        EOG_HASH_ID TEXT,
        CORPORATION_HASH_ID TEXT,
        GENERIC_STATUS_LOCAL_1 TEXT,
        SALES_FLAG BOOLEAN,
        PRODUCT_BRAND TEXT,
        SOURCE_TYPE TEXT,
        DISTRIBUTION_DATA_LEVEL TEXT,
        PRODUCT_LOCAL TEXT,
        STRENGTH TEXT,
        PRODUCT_KEY TEXT,
        CATEGORY_NM TEXT,
        GMID TEXT,
        UPDATED_TS TIMESTAMP,
        PACK TEXT,
        NFC123_LOCAL TEXT,
        CORPORATION_LOCAL TEXT,
        NFC123 TEXT,
        EXCLUSION_FLAG BOOLEAN,
        INSERTED_TS TIMESTAMP,
        CHANNEL_TYPE TEXT,
        PARALLEL_IMPORT_FLAG BOOLEAN,
        COUNTRY TEXT,
        PANEL_ID TEXT,
        SOURCE_PRODUCT_KEY_TMP TEXT,
        ATC_HASH_ID TEXT,
        MOLECULE_LIST TEXT,
        PACK_LAUNCH_DATE DATE,
        SUBNAT_ID TEXT,
        PACK_HASH_ID TEXT,
        RX_STATUS TEXT,
        GENERIC_STATUS TEXT,
        UPC_CD TEXT,
        MANUFACTURER TEXT,
        PACK_LOCAL TEXT,
        MANUFACTURER_HASH_ID TEXT,
        GENERIC_STATUS_LOCAL_2 TEXT,
        CORPORATION TEXT,
        PRODUCT_LAUNCH_DATE DATE,
        PRODUCT_HASH_ID TEXT,
        RX_STATUS_LOCAL TEXT,
        PRODUCT_LOE_DATE DATE,
        ATC4_LOCAL TEXT,
        SUBNAT_DATA_LEVEL TEXT,
        PACK_LOE_DATE DATE,
        PACK_SIZE TEXT,
        PRODUCT TEXT,
        ATC4 TEXT,
        MOLECULE_LIST_LOCAL TEXT,
        DISTRIBUTION_ID TEXT,
        CHC_CLASS TEXT,
        CHC_FORM TEXT
    );
    """)

    # DIM_PANEL
    cursor.execute("""
    CREATE TABLE DIM_PANEL (
        PANEL_ID TEXT PRIMARY KEY,
        COUNTRY TEXT,
        PANEL TEXT,
        CHANNEL TEXT,
        SECTOR TEXT,
        PANEL_GROUP TEXT,
        CHANNEL_GROUP TEXT,
        CHANNEL_LVL_1 TEXT,
        CHANNEL_LVL_2 TEXT,
        CHANNEL_LVL_3 TEXT,
        FREQUENCY TEXT,
        SOURCE TEXT,
        UNIT_TYPE TEXT,
        CLASS_TYPE TEXT,
        SELL_TYPE TEXT,
        AUDIT TEXT,
        VENDOR_NM TEXT,
        WEIGHTAGE REAL,
        PANEL_COVERAGE TEXT,
        MANUFACTURER_RATE REAL,
        TRADE_RATE REAL,
        PUBLIC_RATE REAL,
        DATA_STEWARD_EMAIL TEXT,
        DATA_AVAILABILITY TEXT,
        BUSINESS_OWNER TEXT,
        REQUESTER TEXT,
        SALES_TYPE TEXT,
        LATEST_SALES_PERIOD TEXT,
        CURRENCY_CD TEXT,
        INSERTED_TS TIMESTAMP,
        UPDATED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        ISNEW_FLAG BOOLEAN
    );
    """)

    # DIM_CALENDAR
    cursor.execute("""
    CREATE TABLE DIM_CALENDAR (
        CALENDAR_ID TEXT PRIMARY KEY,
        CALENDAR_TYPE TEXT,
        YEAR INTEGER,
        QUARTER INTEGER,
        QUARTER_NM TEXT,
        MONTH INTEGER,
        MONTH_NM TEXT,
        WEEK INTEGER,
        WEEK_NM TEXT
    );
    """)

    # DIM_COUNTRY
    cursor.execute("""
    CREATE TABLE DIM_COUNTRY (
        COUNTRY_ID TEXT PRIMARY KEY,
        COUNTRY TEXT,
        COUNTRY_SHORT_CD TEXT,
        COUNTRY_SHORT_CD_ALPHA3 TEXT,
        EXCLUSION_FLAG BOOLEAN
    );
    """)

    # DIM_CHANNEL_TYPE
    cursor.execute("""
    CREATE TABLE DIM_CHANNEL_TYPE (
        CHANNEL_TYPE_ID TEXT PRIMARY KEY,
        CHANNEL_TYPE_NM TEXT,
        CHANNEL_TYPE_LVL1 TEXT,
        CHANNEL_TYPE_LVL2 TEXT,
        CHANNEL_TYPE_LVL3 TEXT
    );
    """)

    # DIM_MARKET
    cursor.execute("""
    CREATE TABLE DIM_MARKET (
        MARKET_ID TEXT PRIMARY KEY,
        MARKET_NM TEXT,
        MARKET_LVL_1 TEXT,
        MARKET_LVL_2 TEXT,
        MARKET_LVL_3 TEXT,
        MARKET_LVL_4 TEXT,
        MARKET_LVL_5 TEXT,
        MARKET_LVL_6 TEXT,
        MARKET_LVL_7 TEXT,
        MARKET_LVL_8 TEXT,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN
    );
    """)

    # LNK_MARKET_PRODUCT
    cursor.execute("""
    CREATE TABLE LNK_MARKET_PRODUCT (
        MARKET_PRODUCT_ID TEXT PRIMARY KEY,
        MARKET_ID TEXT,
        SOURCE_PRODUCT_ID TEXT,
        SOURCE_PRODUCT_KEY_TMP TEXT,
        INSERTED_TS TIMESTAMP,
        FOREIGN KEY(MARKET_ID) REFERENCES DIM_MARKET(MARKET_ID),
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID)
    );
    """)

    # DIM_TRANSCODE_PRODUCT
    cursor.execute("""
    CREATE TABLE DIM_TRANSCODE_PRODUCT (
        TRANSCODE_PRODUCT_ID TEXT PRIMARY KEY,
        PRODUCT_KEY TEXT,
        MARKET_NM TEXT,
        COUNTRY TEXT,
        MANUFACTURER TEXT,
        CORPORATION_LOCAL TEXT,
        CORPORATION TEXT,
        PRODUCT TEXT,
        PACK TEXT,
        MOLECULE_LIST TEXT,
        ATC4 TEXT,
        PARALLEL_IMPORT_FLAG BOOLEAN,
        NFC123 TEXT,
        UNIT_TYPE TEXT,
        CORPORATION_GROUP_1 TEXT,
        CORPORATION_GROUP_2 TEXT,
        CORPORATION_GROUP_3 TEXT,
        CORPORATION_GROUP_4 TEXT,
        CORPORATION_GROUP_5 TEXT,
        PRODUCT_GROUP_LOCAL TEXT,
        HARMONIZED_PRODUCT_GROUP TEXT,
        HARMONIZED_PRODUCT_GROUP_INPUT TEXT,
        PRODUCT_GROUP_1 TEXT,
        PRODUCT_GROUP_2 TEXT,
        PRODUCT_GROUP_3 TEXT,
        PRODUCT_GROUP_3A TEXT,
        PRODUCT_GROUP_3B TEXT,
        PRODUCT_GROUP_3C TEXT,
        PRODUCT_GROUP_4 TEXT,
        PRODUCT_GROUP_5 TEXT,
        SU_COEFF REAL,
        IU_COEFF REAL,
        IUE_COEFF REAL,
        TD REAL,
        MG REAL,
        ML REAL,
        SEGMENT TEXT,
        PEQ REAL,
        MOD TEXT,
        BOOST_COMBO TEXT,
        ENTRY_MARKET TEXT,
        ENTRY_MARKET_AMEA TEXT,
        ENTRY_MARKET_LOCAL TEXT,
        REGION_LOCAL TEXT,
        ZONE_LOCAL TEXT,
        SEGMENT_LOCAL TEXT,
        PACK_STD_ML REAL,
        INSERTED_TS TIMESTAMP,
        CODED_BY TEXT,
        CODED_DATE DATE,
        ISNEW_FLAG BOOLEAN,
        EXCLUSION_FLAG BOOLEAN
    );
    """)

    # FACT TABLES --
    
    # FCT_SALES_NATIONAL_MTH
    cursor.execute("""
    CREATE TABLE FCT_SALES_NATIONAL_MTH (
        SOURCE_PRODUCT_ID TEXT,
        COUNTRY_ID TEXT,
        PANEL_ID TEXT,
        CHANNEL_TYPE_ID TEXT,
        EOG_HASH_ID TEXT,
        CALENDAR_ID TEXT,
        QTY_UNITS REAL,
        QTY_SU REAL,
        VALUE_LC REAL,
        VALUE_RX REAL,
        VALUE_MNF_LC REAL,
        VALUE_TRADE_LC REAL,
        VALUE_PUBLIC_LC REAL,
        VALUE_MNF_EU REAL,
        VALUE_TRADE_EU REAL,
        VALUE_PUBLIC_EU REAL,
        QTY_CU REAL,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID),
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(PANEL_ID) REFERENCES DIM_PANEL(PANEL_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    # FCT_SALES_NATIONAL_WK
    cursor.execute("""
    CREATE TABLE FCT_SALES_NATIONAL_WK (
        SOURCE_PRODUCT_ID TEXT,
        COUNTRY_ID TEXT,
        PANEL_ID TEXT,
        CHANNEL_TYPE_ID TEXT,
        EOG_HASH_ID TEXT,
        CALENDAR_ID TEXT,
        QTY_UNITS REAL,
        QTY_SU REAL,
        VALUE_LC REAL,
        VALUE_RX REAL,
        VALUE_MNF_LC REAL,
        VALUE_TRADE_LC REAL,
        VALUE_PUBLIC_LC REAL,
        VALUE_MNF_EU REAL,
        VALUE_TRADE_EU REAL,
        VALUE_PUBLIC_EU REAL,
        QTY_CU REAL,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID),
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(PANEL_ID) REFERENCES DIM_PANEL(PANEL_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    # FCT_SALES_NATIONAL_QTR
    cursor.execute("""
    CREATE TABLE FCT_SALES_NATIONAL_QTR (
        SOURCE_PRODUCT_ID TEXT,
        COUNTRY_ID TEXT,
        PANEL_ID TEXT,
        CHANNEL_TYPE_ID TEXT,
        EOG_HASH_ID TEXT,
        CALENDAR_ID TEXT,
        QTY_UNITS REAL,
        QTY_SU REAL,
        VALUE_LC REAL,
        VALUE_RX REAL,
        VALUE_MNF_LC REAL,
        VALUE_TRADE_LC REAL,
        VALUE_PUBLIC_LC REAL,
        VALUE_MNF_EU REAL,
        VALUE_TRADE_EU REAL,
        VALUE_PUBLIC_EU REAL,
        QTY_CU REAL,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID),
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(PANEL_ID) REFERENCES DIM_PANEL(PANEL_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    # FCT_CURRENCY_EXCHANGE_RATE
    cursor.execute("""
    CREATE TABLE FCT_CURRENCY_EXCHANGE_RATE (
        EXCHANGE_RATE_ID TEXT PRIMARY KEY,
        COUNTRY_ID TEXT,
        PANEL TEXT,
        CURRENCY_CD TEXT,
        EXCHANGE_RATE_TYPE TEXT,
        EXCHANGE_RATE_TYPE_DESC TEXT,
        CALENDAR_ID TEXT,
        EXCHANGE_RATE REAL,
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    # FCT_SUB_NATIONAL
    cursor.execute("""
    CREATE TABLE FCT_SUB_NATIONAL (
        SUBNAT_PRODUCT_ID TEXT PRIMARY KEY,
        SOURCE_PRODUCT_ID TEXT,
        COUNTRY_ID TEXT,
        GEO_ID TEXT,
        PANEL_ID TEXT,
        CALENDAR_ID TEXT,
        FREQUENCY TEXT,
        CHANNEL_TYPE_ID TEXT,
        QTY_UNITS REAL,
        QTY_SU REAL,
        QTY_CU REAL,
        VALUE_LC REAL,
        VALUE_RX REAL,
        VALUE_MNF_LC REAL,
        VALUE_TRADE_LC REAL,
        VALUE_PUBLIC_LC REAL,
        VALUE_MNF_EU REAL,
        VALUE_TRADE_EU REAL,
        VALUE_PUBLIC_EU REAL,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID),
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(PANEL_ID) REFERENCES DIM_PANEL(PANEL_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    # FCT_DISTRIBUTION
    cursor.execute("""
    CREATE TABLE FCT_DISTRIBUTION (
        DISTRIBUTION_ID TEXT PRIMARY KEY,
        COUNTRY_ID TEXT,
        GEO_ID TEXT,
        GEO_LVL TEXT,
        PANEL_ID TEXT,
        CHANNEL_TYPE_ID TEXT,
        SOURCE_PRODUCT_ID TEXT,
        FREQUENCY TEXT,
        DATA_LEVEL TEXT,
        CALENDAR_ID TEXT,
        NUM_DISTRIBUTION_SELLOUT REAL,
        WTD_DISTRIBUTION_SELLOUT REAL,
        NUM_DISTRIBUTION_STOCK REAL,
        WTD_DISTRIBUTION_STOCK REAL,
        INSERTED_TS TIMESTAMP,
        EXCLUSION_FLAG BOOLEAN,
        BANNER_ID TEXT,
        FOREIGN KEY(COUNTRY_ID) REFERENCES DIM_COUNTRY(COUNTRY_ID),
        FOREIGN KEY(PANEL_ID) REFERENCES DIM_PANEL(PANEL_ID),
        FOREIGN KEY(SOURCE_PRODUCT_ID) REFERENCES DIM_SOURCE_PRODUCT(SOURCE_PRODUCT_ID),
        FOREIGN KEY(CALENDAR_ID) REFERENCES DIM_CALENDAR(CALENDAR_ID)
    );
    """)

    print("Tables created successfully.")
    
    # Optional: Insert some dummy data
    print("Inserting dummy data...")
    
    cursor.execute("INSERT INTO DIM_COUNTRY (COUNTRY_ID, COUNTRY, COUNTRY_SHORT_CD) VALUES ('US', 'United States', 'USA')")
    cursor.execute("INSERT INTO DIM_CALENDAR (CALENDAR_ID, YEAR, MONTH, QUARTER) VALUES ('202301', 2023, 1, 1)")
    cursor.execute("INSERT INTO DIM_PANEL (PANEL_ID, PANEL, COUNTRY) VALUES ('P1', 'Retail Panel', 'United States')")
    # Insert Brands
    brands = [
        ('SP1', 'Allegra', 'Pain Relief'),
        ('SP2', 'Advil', 'Pain Relief'),
        ('SP3', 'Tylenol', 'Pain Relief'),
        ('SP4', 'Zyrtec', 'Allergy'),
        ('SP5', 'Claritin', 'Allergy'),
        ('SP6', 'Doliprane', 'Pain Relief'),
        ('SP7', 'Dulcoflex', 'Digestive Health')
    ]
    
    cursor.executemany("INSERT INTO DIM_SOURCE_PRODUCT (SOURCE_PRODUCT_ID, PRODUCT_BRAND, CATEGORY_NM) VALUES (?, ?, ?)", brands)

    # Insert Sales Data
    sales_data = [
        ('SP1', 'US', 'P1', '202301', 1000.0, 500),
        ('SP2', 'US', 'P1', '202301', 1500.0, 750),
        ('SP3', 'US', 'P1', '202301', 1200.0, 600),
        ('SP4', 'US', 'P1', '202301', 900.0, 450),
        ('SP5', 'US', 'P1', '202301', 1100.0, 550),
        ('SP6', 'US', 'P1', '202301', 850.0, 400),
        ('SP7', 'US', 'P1', '202301', 600.0, 300)
    ]

    cursor.executemany("INSERT INTO FCT_SALES_NATIONAL_MTH (SOURCE_PRODUCT_ID, COUNTRY_ID, PANEL_ID, CALENDAR_ID, VALUE_LC, QTY_UNITS) VALUES (?, ?, ?, ?, ?, ?)", sales_data)
    
    conn.commit()
    conn.close()
    print("Database initialized at", DB_PATH)

if __name__ == "__main__":
    create_db()
